import type { Analytics, Category, Order, Product, StoreSettings } from "@/lib/types";

export const categories: Category[] = [
  { id: "cat-rice", name: "Rice Meals", slug: "rice-meals", sort_order: 1 },
  { id: "cat-drinks", name: "Shakes & Soda", slug: "shakes-soda", sort_order: 2 },
  { id: "cat-snacks", name: "Snacks", slug: "snacks", sort_order: 3 }
];

export const settings: StoreSettings = {
  store_name: "ARJT Store",
  store_open: true,
  opening_time: "06:30",
  closing_time: "18:30",
  delivery_fee: 10,
  gcash_name: "ARJT Store",
  gcash_number: "0917 123 4567",
  gcash_qr_url: "/gcash-qr.svg",
  default_prep_minutes: 12,
  banner_url:
    "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80"
};

const img = (query: string) =>
  `https://images.unsplash.com/photo-${query}?auto=format&fit=crop&w=900&q=80`;

export const products: Product[] = [
  // Rice Meals
  {
    id: "prod-1",
    category_id: "cat-rice",
    name: "Tapsilog (Beef)",
    slug: "tapsilog-beef",
    description: "Beef tapa, garlic rice, and egg.",
    price: 110,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 12,
    sold_today: 22,
    options: []
  },
  {
    id: "prod-2",
    category_id: "cat-rice",
    name: "Tocilog",
    slug: "tocilog",
    description: "Cured pork, garlic rice, and egg.",
    price: 100,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 12,
    sold_today: 18,
    options: []
  },
  {
    id: "prod-3",
    category_id: "cat-rice",
    name: "Porksilog",
    slug: "porksilog",
    description: "Fried pork, garlic rice, and egg.",
    price: 105,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 12,
    sold_today: 20,
    options: []
  },
  {
    id: "prod-4",
    category_id: "cat-rice",
    name: "Sisilog",
    slug: "sisilog",
    description: "Fish (tuyo), garlic rice, and egg.",
    price: 110,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 12,
    sold_today: 14,
    options: []
  },
  {
    id: "prod-5",
    category_id: "cat-rice",
    name: "Bangsilog",
    slug: "bangsilog",
    description: "Milkfish (bangus), garlic rice, and egg.",
    price: 100,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 12,
    sold_today: 12,
    options: []
  },
  {
    id: "prod-6",
    category_id: "cat-rice",
    name: "Chicksilog",
    slug: "chicksilog",
    description: "Fried chicken, garlic rice, and egg.",
    price: 100,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 13,
    sold_today: 25,
    options: []
  },
  {
    id: "prod-7",
    category_id: "cat-rice",
    name: "Hotsilog",
    slug: "hotsilog",
    description: "Hotdog, garlic rice, and egg.",
    price: 70,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 10,
    sold_today: 16,
    options: []
  },
  {
    id: "prod-8",
    category_id: "cat-rice",
    name: "Hotdog w/ Rice",
    slug: "hotdog-with-rice",
    description: "Hotdog and garlic rice.",
    price: 55,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 8,
    sold_today: 11,
    options: []
  },
  {
    id: "prod-9",
    category_id: "cat-rice",
    name: "Siomai w/ Rice",
    slug: "siomai-with-rice",
    description: "Siomai dumplings with garlic rice.",
    price: 50,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 9,
    sold_today: 10,
    options: []
  },
  {
    id: "prod-10",
    category_id: "cat-rice",
    name: "Rice w/ Egg",
    slug: "rice-with-egg",
    description: "Garlic rice with fried egg.",
    price: 45,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 7,
    sold_today: 8,
    options: []
  },
  {
    id: "prod-11",
    category_id: "cat-rice",
    name: "Chicken Fillet",
    slug: "chicken-fillet",
    description: "Breaded chicken fillet with rice.",
    price: 90,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 12,
    sold_today: 19,
    options: []
  },
  {
    id: "prod-12",
    category_id: "cat-rice",
    name: "Chicken Dumpling w/ Rice",
    slug: "chicken-dumpling-with-rice",
    description: "Chicken dumplings with garlic rice.",
    price: 65,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 10,
    sold_today: 9,
    options: []
  },
  {
    id: "prod-13",
    category_id: "cat-rice",
    name: "Chicken Nuggets w/ Rice",
    slug: "chicken-nuggets-with-rice",
    description: "Chicken nuggets with garlic rice.",
    price: 85,
    image_url: img("1604908176997-125f25cc6f3d"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 10,
    sold_today: 17,
    options: []
  },
  // Shakes & Soda
  {
    id: "prod-14",
    category_id: "cat-drinks",
    name: "Mango Shake",
    slug: "mango-shake",
    description: "Fresh mango shake (16oz).",
    price: 50,
    image_url: img("1599599810694-c0e19dfc8b4b"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 5,
    sold_today: 24,
    options: []
  },
  {
    id: "prod-15",
    category_id: "cat-drinks",
    name: "Strawberry Shake",
    slug: "strawberry-shake",
    description: "Fresh strawberry shake (16oz).",
    price: 50,
    image_url: img("1599599810694-c0e19dfc8b4b"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 5,
    sold_today: 21,
    options: []
  },
  {
    id: "prod-16",
    category_id: "cat-drinks",
    name: "Buko Shake",
    slug: "buko-shake",
    description: "Coconut shake (16oz).",
    price: 50,
    image_url: img("1599599810694-c0e19dfc8b4b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 5,
    sold_today: 12,
    options: []
  },
  {
    id: "prod-17",
    category_id: "cat-drinks",
    name: "Melon Shake",
    slug: "melon-shake",
    description: "Sweet melon shake (16oz).",
    price: 50,
    image_url: img("1599599810694-c0e19dfc8b4b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 5,
    sold_today: 10,
    options: []
  },
  {
    id: "prod-18",
    category_id: "cat-drinks",
    name: "Halo-Halo Shake",
    slug: "halo-halo-shake",
    description: "Mixed ingredients shake with halo-halo flavor (16oz).",
    price: 60,
    image_url: img("1578985545062-69928b1d9587"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 6,
    sold_today: 15,
    options: []
  },
  {
    id: "prod-19",
    category_id: "cat-drinks",
    name: "Mais Con Yelo",
    slug: "mais-con-yelo",
    description: "Sweet corn with evaporated milk and crushed ice.",
    price: 55,
    image_url: img("1599599810694-c0e19dfc8b4b"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 5,
    sold_today: 18,
    options: []
  },
  {
    id: "prod-20",
    category_id: "cat-drinks",
    name: "Strawberry Soda",
    slug: "strawberry-soda",
    description: "Strawberry fruit soda.",
    price: 50,
    image_url: img("1599599810694-c0e19dfc8b4b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 3,
    sold_today: 9,
    options: []
  },
  {
    id: "prod-21",
    category_id: "cat-drinks",
    name: "Kiwi Soda",
    slug: "kiwi-soda",
    description: "Kiwi fruit soda.",
    price: 50,
    image_url: img("1599599810694-c0e19dfc8b4b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 3,
    sold_today: 7,
    options: []
  },
  {
    id: "prod-22",
    category_id: "cat-drinks",
    name: "Green Apple Soda",
    slug: "green-apple-soda",
    description: "Green apple fruit soda.",
    price: 50,
    image_url: img("1599599810694-c0e19dfc8b4b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 3,
    sold_today: 8,
    options: []
  },
  {
    id: "prod-23",
    category_id: "cat-drinks",
    name: "Lychee Soda",
    slug: "lychee-soda",
    description: "Lychee fruit soda.",
    price: 50,
    image_url: img("1599599810694-c0e19dfc8b4b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 3,
    sold_today: 6,
    options: []
  },
  // Snacks
  {
    id: "prod-24",
    category_id: "cat-snacks",
    name: "Regular Burger",
    slug: "regular-burger",
    description: "Classic burger with bun and patty.",
    price: 45,
    image_url: img("1606755962773-d324e2dabd85"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 7,
    sold_today: 20,
    options: []
  },
  {
    id: "prod-25",
    category_id: "cat-snacks",
    name: "Burger w/ Cheese",
    slug: "burger-with-cheese",
    description: "Burger with melted cheese.",
    price: 50,
    image_url: img("1606755962773-d324e2dabd85"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 8,
    sold_today: 23,
    options: []
  },
  {
    id: "prod-26",
    category_id: "cat-snacks",
    name: "Hotdog Burger",
    slug: "hotdog-burger",
    description: "Burger with hotdog instead of patty.",
    price: 50,
    image_url: img("1606755962773-d324e2dabd85"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 7,
    sold_today: 19,
    options: []
  },
  {
    id: "prod-27",
    category_id: "cat-snacks",
    name: "Fries",
    slug: "fries",
    description: "Crispy golden fries with salt.",
    price: 25,
    image_url: img("1586190936837-c6cea6bab31d"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 6,
    sold_today: 35,
    options: []
  },
  {
    id: "prod-28",
    category_id: "cat-snacks",
    name: "Fish Tofu",
    slug: "fish-tofu",
    description: "Crispy fried tofu with fish flavor.",
    price: 30,
    image_url: img("1546069901-ba9ca3e87f0f"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 8,
    sold_today: 11,
    options: []
  },
  {
    id: "prod-29",
    category_id: "cat-snacks",
    name: "Squidballs",
    slug: "squidballs",
    description: "Deep-fried squid balls.",
    price: 20,
    image_url: img("1574521251149-2c89a40e5b5b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 6,
    sold_today: 13,
    options: []
  },
  {
    id: "prod-30",
    category_id: "cat-snacks",
    name: "Hotdog on Stick",
    slug: "hotdog-on-stick",
    description: "Breaded hotdog on a stick.",
    price: 20,
    image_url: img("1614432547174-e0fc56d06f9e"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 5,
    sold_today: 17,
    options: []
  },
  {
    id: "prod-31",
    category_id: "cat-snacks",
    name: "Siomai Pork",
    slug: "siomai-pork",
    description: "Pork siomai dumplings.",
    price: 25,
    image_url: img("1612929633738-8fe44f7ec841"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 7,
    sold_today: 14,
    options: []
  },
  {
    id: "prod-32",
    category_id: "cat-snacks",
    name: "Siomai Beef",
    slug: "siomai-beef",
    description: "Beef siomai dumplings.",
    price: 25,
    image_url: img("1612929633738-8fe44f7ec841"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 7,
    sold_today: 12,
    options: []
  },
  {
    id: "prod-33",
    category_id: "cat-snacks",
    name: "Siomai Japanese",
    slug: "siomai-japanese",
    description: "Japanese-style siomai dumplings.",
    price: 30,
    image_url: img("1612929633738-8fe44f7ec841"),
    is_available: true,
    is_popular: true,
    prep_time_minutes: 8,
    sold_today: 16,
    options: []
  },
  {
    id: "prod-34",
    category_id: "cat-snacks",
    name: "Kikiam",
    slug: "kikiam",
    description: "Fried meat roll.",
    price: 20,
    image_url: img("1574521251149-2c89a40e5b5b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 6,
    sold_today: 15,
    options: []
  },
  {
    id: "prod-35",
    category_id: "cat-snacks",
    name: "Kwik-Kwik",
    slug: "kwik-kwik",
    description: "Fried snack stick.",
    price: 20,
    image_url: img("1574521251149-2c89a40e5b5b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 6,
    sold_today: 13,
    options: []
  },
  {
    id: "prod-36",
    category_id: "cat-snacks",
    name: "Fishball",
    slug: "fishball",
    description: "Deep-fried fishball.",
    price: 20,
    image_url: img("1574521251149-2c89a40e5b5b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 5,
    sold_today: 18,
    options: []
  },
  {
    id: "prod-37",
    category_id: "cat-snacks",
    name: "Dynamite",
    slug: "dynamite",
    description: "Spicy fried snack.",
    price: 20,
    image_url: img("1574521251149-2c89a40e5b5b"),
    is_available: true,
    is_popular: false,
    prep_time_minutes: 6,
    sold_today: 10,
    options: []
  }
].map((product) => ({ ...product, category: categories.find((item) => item.id === product.category_id) }));

export const orders: Order[] = [
  {
    id: "ord-1001",
    queue_number: 14,
    customer_name: "Mika Santos",
    contact_number: "09171234567",
    grade_section: "10 - Rizal",
    fulfillment_type: "pickup",
    desired_time: new Date().toISOString(),
    notes: "Pickup during lunch break.",
    status: "preparing",
    subtotal: 160,
    delivery_fee: 0,
    total: 160,
    estimated_ready_at: new Date(Date.now() + 8 * 60000).toISOString(),
    created_at: new Date(Date.now() - 12 * 60000).toISOString(),
    order_items: [
      {
        id: "oi-1",
        order_id: "ord-1001",
        product_id: "prod-25",
        product_name: "Burger w/ Cheese",
        quantity: 1,
        unit_price: 50,
        options_total: 0,
        selected_options: []
      },
      {
        id: "oi-2",
        order_id: "ord-1001",
        product_id: "prod-1",
        product_name: "Tapsilog (Beef)",
        quantity: 1,
        unit_price: 110,
        options_total: 0,
        selected_options: []
      }
    ],
    payments: [{ id: "pay-1", order_id: "ord-1001", status: "pending_verification", amount: 160 }]
  }
];

export const analytics: Analytics = {
  ordersToday: 62,
  revenueToday: 5240,
  pendingOrders: 8,
  completedOrders: 54,
  mostOrderedProduct: "Fries",
  dailySales: [
    { label: "Mon", revenue: 3800, orders: 38 },
    { label: "Tue", revenue: 4500, orders: 52 },
    { label: "Wed", revenue: 4200, orders: 45 },
    { label: "Thu", revenue: 5100, orders: 58 },
    { label: "Fri", revenue: 5240, orders: 62 }
  ],
  bestSellers: [
    { name: "Fries", sold: 35 },
    { name: "Tapsilog (Beef)", sold: 22 },
    { name: "Burger w/ Cheese", sold: 23 },
    { name: "Mango Shake", sold: 24 }
  ],
  busyHours: [
    { hour: "9 AM", orders: 8 },
    { hour: "10 AM", orders: 12 },
    { hour: "11 AM", orders: 31 },
    { hour: "12 PM", orders: 45 },
    { hour: "1 PM", orders: 20 },
    { hour: "4 PM", orders: 26 }
  ]
};
